# Amira Project 670
# Amira
# Generated by Amira 6.7.0
remove -all
remove "grayScale.am" "physics.icol" "labels.am" "JRC2018_UNISEX_38um_iso_16bit.nrrd" "JRC2018_UNISEX_38um_iso_16bit.to-byte" "JRC2018_UNISEX_38um_iso_16bit.resampled" "JRC2018_UNISEX_38um_iso_16bit.labels" "JRC2018_UNISEX_38um_iso_16bit.surf" "JRC2018_UNISEX_38um_iso_16bit.smooth.surf.100k.am" "JRC2018_UNISEX_38um_iso_16bit.smooth.surf.25k.surf" "JRC2018_UNISEX_38um_iso_16bit.smooth.surf.18k.surf" "Light" "Ortho Slice" "Convert Image Type" "Resample" "Multi-Thresholding" "Generate Surface" "Surface View" "Smooth Surface"

# Create viewers
viewer setVertical 0

viewer 0 setTransparencyType 6
viewer 0 setAutoRedraw 0
viewer 0 show
mainWindow show

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/grayScale.am ] setLabel "grayScale.am"
"grayScale.am" setIconPosition 0 0
"grayScale.am" setNoRemoveAll 1
"grayScale.am" setVar "CustomHelp" {HxColormap256}
"grayScale.am" fire
"grayScale.am" setMinMax 0 255
"grayScale.am" flags setValue 1
"grayScale.am" shift setMinMax -1 1
"grayScale.am" shift setButtons 0
"grayScale.am" shift setEditButton 1
"grayScale.am" shift setIncrement 0.133333
"grayScale.am" shift setValue 0
"grayScale.am" shift setSubMinMax -1 1
"grayScale.am" scale setMinMax 0 1
"grayScale.am" scale setButtons 0
"grayScale.am" scale setEditButton 1
"grayScale.am" scale setIncrement 0.1
"grayScale.am" scale setValue 1
"grayScale.am" scale setSubMinMax 0 1
"grayScale.am" fire
"grayScale.am" setViewerMask 16383

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/physics.icol ] setLabel "physics.icol"
"physics.icol" setIconPosition 0 0
"physics.icol" setNoRemoveAll 1
"physics.icol" fire
"physics.icol" setMinMax 0 1
"physics.icol" flags setValue 1
"physics.icol" shift setMinMax -1 1
"physics.icol" shift setButtons 0
"physics.icol" shift setEditButton 1
"physics.icol" shift setIncrement 0.133333
"physics.icol" shift setValue 0
"physics.icol" shift setSubMinMax -1 1
"physics.icol" scale setMinMax 0 1
"physics.icol" scale setButtons 0
"physics.icol" scale setEditButton 1
"physics.icol" scale setIncrement 0.1
"physics.icol" scale setValue 1
"physics.icol" scale setSubMinMax 0 1
"physics.icol" fire
"physics.icol" setViewerMask 16383

set hideNewModules 1
[ load ${AMIRA_ROOT}/data/colormaps/labels.am ] setLabel "labels.am"
"labels.am" setIconPosition 0 0
"labels.am" setNoRemoveAll 1
"labels.am" setVar "CustomHelp" {HxColormap256}
"labels.am" fire
"labels.am" setMinMax 1 8
"labels.am" flags setValue 1
"labels.am" shift setMinMax -1 1
"labels.am" shift setButtons 0
"labels.am" shift setEditButton 1
"labels.am" shift setIncrement 0.133333
"labels.am" shift setValue 0
"labels.am" shift setSubMinMax -1 1
"labels.am" scale setMinMax 0 1
"labels.am" scale setButtons 0
"labels.am" scale setEditButton 1
"labels.am" scale setIncrement 0.1
"labels.am" scale setValue 1
"labels.am" scale setSubMinMax 0 1
"labels.am" fire
"labels.am" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/JRC2018_UNISEX_38um_iso_16bit.nrrd ] setLabel "JRC2018_UNISEX_38um_iso_16bit.nrrd"
"JRC2018_UNISEX_38um_iso_16bit.nrrd" setIconPosition 19 10
"JRC2018_UNISEX_38um_iso_16bit.nrrd" sharedColormap disconnect
"JRC2018_UNISEX_38um_iso_16bit.nrrd" sharedColormap setDefaultColor 0.8 0.8 0.8
"JRC2018_UNISEX_38um_iso_16bit.nrrd" sharedColormap setDefaultAlpha 0.500000
"JRC2018_UNISEX_38um_iso_16bit.nrrd" sharedColormap activateLocalRange 1
"JRC2018_UNISEX_38um_iso_16bit.nrrd" sharedColormap setLocalMinMax 0.000000 1.000000
"JRC2018_UNISEX_38um_iso_16bit.nrrd" sharedColormap enableAlpha 1
"JRC2018_UNISEX_38um_iso_16bit.nrrd" sharedColormap enableAlphaToggle 1
"JRC2018_UNISEX_38um_iso_16bit.nrrd" sharedColormap setAutoAdjustRangeMode 1
"JRC2018_UNISEX_38um_iso_16bit.nrrd" sharedColormap setColorbarMinMax 0 120
"JRC2018_UNISEX_38um_iso_16bit.nrrd" fire
"JRC2018_UNISEX_38um_iso_16bit.nrrd" fire
"JRC2018_UNISEX_38um_iso_16bit.nrrd" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/JRC2018_UNISEX_38um_iso_16bit.smooth.surf.25k.surf ] setLabel "JRC2018_UNISEX_38um_iso_16bit.smooth.surf.25k.surf"
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.25k.surf" setIconPosition 20 467
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.25k.surf" fire
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.25k.surf" LevelOfDetail setMinMax -1 -1
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.25k.surf" LevelOfDetail setButtons 1
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.25k.surf" LevelOfDetail setEditButton 1
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.25k.surf" LevelOfDetail setIncrement 1
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.25k.surf" LevelOfDetail setValue -1
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.25k.surf" LevelOfDetail setSubMinMax -1 -1
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.25k.surf" fire
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.25k.surf" setViewerMask 16383

set hideNewModules 0
[ load ${SCRIPTDIR}/JRC2018_UNISEX_38um_iso_16bit.smooth.surf.18k.surf ] setLabel "JRC2018_UNISEX_38um_iso_16bit.smooth.surf.18k.surf"
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.18k.surf" setIconPosition 20 503
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.18k.surf" fire
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.18k.surf" LevelOfDetail setMinMax -1 -1
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.18k.surf" LevelOfDetail setButtons 1
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.18k.surf" LevelOfDetail setEditButton 1
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.18k.surf" LevelOfDetail setIncrement 1
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.18k.surf" LevelOfDetail setValue -1
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.18k.surf" LevelOfDetail setSubMinMax -1 -1
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.18k.surf" fire
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.18k.surf" setViewerMask 16383
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.18k.surf" select

set hideNewModules 0
create HxLight "Light"
"Light" setIconPosition 493 10
"Light" setNoRemoveAll 1
"Light" setType 0
"Light" setColor 1 1 1
"Light" setSlave 1
"Light" edit 1
"Light" setDirection 0.0173025 0.0876986 -0.995997
"Light" setLocation 3.87322 -15.8212 17.3777
"Light" setIntensity 1
"Light" fire
"Light" setViewerMask 16383

set hideNewModules 0
create HxOrthoSlice "Ortho Slice"
"Ortho Slice" setIconPosition 302 53
"Ortho Slice" setVar "CustomHelp" {HxOrthoSlice}
"Ortho Slice" data connect "JRC2018_UNISEX_38um_iso_16bit.nrrd"
"Ortho Slice" fire
"Ortho Slice" sliceOrientation setValue 0
"Ortho Slice" fire
"Ortho Slice" origin  setBoundingBox -3.40282e+38 3.40282e+38 -3.40282e+38 3.40282e+38 -3.40282e+38 3.40282e+38
"Ortho Slice" origin  setImmediateMode 0
"Ortho Slice" origin  setOrtho 0
"Ortho Slice" origin  showDragger 0
"Ortho Slice" origin  showPoints 0
"Ortho Slice" origin  setPointScale 1
"Ortho Slice" origin  showOptionButton 1
"Ortho Slice" origin  setNumPoints 1 1 1
"Ortho Slice" origin  setCoord 0 313.69 146.68 80.94
"Ortho Slice" normal  setBoundingBox -3.40282e+38 3.40282e+38 -3.40282e+38 3.40282e+38 -3.40282e+38 3.40282e+38
"Ortho Slice" normal  setImmediateMode 0
"Ortho Slice" normal  setOrtho 0
"Ortho Slice" normal  showDragger 0
"Ortho Slice" normal  showPoints 0
"Ortho Slice" normal  setPointScale 1
"Ortho Slice" normal  showOptionButton 1
"Ortho Slice" normal  setNumPoints 1 1 1
"Ortho Slice" normal  setCoord 0 0 0 1
"Ortho Slice" options setValue 0 1
"Ortho Slice" options setToggleVisible 0 1
"Ortho Slice" options setValue 1 0
"Ortho Slice" options setToggleVisible 1 1
"Ortho Slice" options setValue 2 0
"Ortho Slice" options setToggleVisible 2 1
"Ortho Slice" mappingType setIndex 0 0
"Ortho Slice" contrastLimit setMinMax 0 -16777216 16777216
"Ortho Slice" contrastLimit setValue 0 7
"Ortho Slice" colormap connect "grayScale.am"
"Ortho Slice" colormap setDefaultColor 1 0.8 0.5
"Ortho Slice" colormap setDefaultAlpha 1.000000
"Ortho Slice" colormap activateLocalRange 1
"Ortho Slice" colormap setLocalMinMax 0.000000 19288.000000
"Ortho Slice" colormap enableAlpha 1
"Ortho Slice" colormap enableAlphaToggle 1
"Ortho Slice" colormap setAutoAdjustRangeMode 1
"Ortho Slice" colormap setColorbarMinMax 0 64000
"Ortho Slice" sliceNumber setMinMax 0 455
"Ortho Slice" sliceNumber setButtons 1
"Ortho Slice" sliceNumber setEditButton 1
"Ortho Slice" sliceNumber setIncrement 1
"Ortho Slice" sliceNumber setValue 213
"Ortho Slice" sliceNumber setSubMinMax 0 455
"Ortho Slice" transparency setValue 0
"Ortho Slice" alpha setMinMax 0 -16777216 16777216
"Ortho Slice" alpha setValue 0 0
"Ortho Slice" alpha setMinMax 1 -16777216 16777216
"Ortho Slice" alpha setValue 1 255
"Ortho Slice" frameSettings setState {item 0 1 item 2 1 color 3 1 0.5 0 }
"Ortho Slice" embossingOnOff setValue 0
"Ortho Slice" depth setMinMax -60 60
"Ortho Slice" depth setButtons 0
"Ortho Slice" depth setEditButton 1
"Ortho Slice" depth setIncrement 8
"Ortho Slice" depth setValue 2
"Ortho Slice" depth setSubMinMax -60 60
"Ortho Slice" fire

"Ortho Slice" fire
"Ortho Slice" setViewerMask 16383
"Ortho Slice" setShadowStyle 0
"Ortho Slice" setPickable 1

set hideNewModules 0
create HxCastField "Convert Image Type"
"Convert Image Type" setIconPosition 122 85
"Convert Image Type" setVar "CustomHelp" {HxCastField}
"Convert Image Type" data connect "JRC2018_UNISEX_38um_iso_16bit.nrrd"
"Convert Image Type" colormap disconnect
"Convert Image Type" colormap setDefaultColor 1 0.8 0.5
"Convert Image Type" colormap setDefaultAlpha 0.500000
"Convert Image Type" colormap activateLocalRange 1
"Convert Image Type" colormap setLocalMinMax 0.000000 30306.000000
"Convert Image Type" colormap enableAlpha 1
"Convert Image Type" colormap enableAlphaToggle 1
"Convert Image Type" colormap setAutoAdjustRangeMode 1
"Convert Image Type" colormap setColorbarMinMax 0 30306
"Convert Image Type" fire
"Convert Image Type" outputType setIndex 0 0
"Convert Image Type" scaling setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
"Convert Image Type" scaling setValue 0 0.00840336084365845
"Convert Image Type" scaling setMinMax 1 -3.40282346638529e+38 3.40282346638529e+38
"Convert Image Type" scaling setValue 1 0
"Convert Image Type" voxelGridOptions setValue 0 1
"Convert Image Type" voxelGridOptions setToggleVisible 0 1
"Convert Image Type" colorFieldOptions setIndex 0 0
"Convert Image Type" applyTransformToResult 1
"Convert Image Type" fire
"Convert Image Type" setViewerMask 16383
"Convert Image Type" setPickable 1

set hideNewModules 0
[ {Convert Image Type} create result ] setLabel "JRC2018_UNISEX_38um_iso_16bit.to-byte"
"JRC2018_UNISEX_38um_iso_16bit.to-byte" setIconPosition 20 121
"JRC2018_UNISEX_38um_iso_16bit.to-byte" master connect "Convert Image Type" "result" 0
"JRC2018_UNISEX_38um_iso_16bit.to-byte" sharedColormap disconnect
"JRC2018_UNISEX_38um_iso_16bit.to-byte" sharedColormap setDefaultColor 0.8 0.8 0.8
"JRC2018_UNISEX_38um_iso_16bit.to-byte" sharedColormap setDefaultAlpha 0.500000
"JRC2018_UNISEX_38um_iso_16bit.to-byte" sharedColormap activateLocalRange 1
"JRC2018_UNISEX_38um_iso_16bit.to-byte" sharedColormap setLocalMinMax 0.000000 1.000000
"JRC2018_UNISEX_38um_iso_16bit.to-byte" sharedColormap enableAlpha 1
"JRC2018_UNISEX_38um_iso_16bit.to-byte" sharedColormap enableAlphaToggle 1
"JRC2018_UNISEX_38um_iso_16bit.to-byte" sharedColormap setAutoAdjustRangeMode 1
"JRC2018_UNISEX_38um_iso_16bit.to-byte" sharedColormap setColorbarMinMax 0 254
"JRC2018_UNISEX_38um_iso_16bit.to-byte" fire
"JRC2018_UNISEX_38um_iso_16bit.to-byte" fire
"JRC2018_UNISEX_38um_iso_16bit.to-byte" setViewerMask 16383

set hideNewModules 0
create HxResample "Resample"
"Resample" setIconPosition 160 157
"Resample" setVar "CustomHelp" {HxResample}
"Resample" data connect "JRC2018_UNISEX_38um_iso_16bit.to-byte"
"Resample" fire
"Resample" filter setIndex 0 4
"Resample" mode setValue 1
"Resample" resolution setMinMax 0 1 2147483648
"Resample" resolution setValue 0 314
"Resample" resolution setMinMax 1 1 2147483648
"Resample" resolution setValue 1 147
"Resample" resolution setMinMax 2 1 2147483648
"Resample" resolution setValue 2 87
"Resample" voxelSize setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
"Resample" voxelSize setValue 0 2
"Resample" voxelSize setMinMax 1 -3.40282346638529e+38 3.40282346638529e+38
"Resample" voxelSize setValue 1 2
"Resample" voxelSize setMinMax 2 -3.40282346638529e+38 3.40282346638529e+38
"Resample" voxelSize setValue 2 2
"Resample" average setMinMax 0 1 32
"Resample" average setValue 0 2
"Resample" average setMinMax 1 1 32
"Resample" average setValue 1 2
"Resample" average setMinMax 2 1 32
"Resample" average setValue 2 1
"Resample" applyTransformToResult 1
"Resample" fire
"Resample" setViewerMask 16383
"Resample" setPickable 1

set hideNewModules 0
[ {Resample} create result ] setLabel "JRC2018_UNISEX_38um_iso_16bit.resampled"
"JRC2018_UNISEX_38um_iso_16bit.resampled" setIconPosition 20 192
"JRC2018_UNISEX_38um_iso_16bit.resampled" master connect "Resample" "result" 0
"JRC2018_UNISEX_38um_iso_16bit.resampled" sharedColormap disconnect
"JRC2018_UNISEX_38um_iso_16bit.resampled" sharedColormap setDefaultColor 0.8 0.8 0.8
"JRC2018_UNISEX_38um_iso_16bit.resampled" sharedColormap setDefaultAlpha 0.500000
"JRC2018_UNISEX_38um_iso_16bit.resampled" sharedColormap activateLocalRange 1
"JRC2018_UNISEX_38um_iso_16bit.resampled" sharedColormap setLocalMinMax 0.000000 1.000000
"JRC2018_UNISEX_38um_iso_16bit.resampled" sharedColormap enableAlpha 1
"JRC2018_UNISEX_38um_iso_16bit.resampled" sharedColormap enableAlphaToggle 1
"JRC2018_UNISEX_38um_iso_16bit.resampled" sharedColormap setAutoAdjustRangeMode 1
"JRC2018_UNISEX_38um_iso_16bit.resampled" sharedColormap setColorbarMinMax 0 1
"JRC2018_UNISEX_38um_iso_16bit.resampled" fire
"JRC2018_UNISEX_38um_iso_16bit.resampled" setTransform 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 1
"JRC2018_UNISEX_38um_iso_16bit.resampled" fire
"JRC2018_UNISEX_38um_iso_16bit.resampled" setViewerMask 16383

set hideNewModules 0
create HxLabelVoxel "Multi-Thresholding"
"Multi-Thresholding" setIconPosition 162 231
"Multi-Thresholding" setVar "CustomHelp" {HxLabelVoxel}
"Multi-Thresholding" data connect "JRC2018_UNISEX_38um_iso_16bit.resampled"
"Multi-Thresholding" fire
"Multi-Thresholding" regions setState {Exterior Inside}
"Multi-Thresholding" boundary01 setMinMax 0 228
"Multi-Thresholding" boundary01 setButtons 1
"Multi-Thresholding" boundary01 setEditButton 1
"Multi-Thresholding" boundary01 setIncrement 10
"Multi-Thresholding" boundary01 setValue 20
"Multi-Thresholding" boundary01 setSubMinMax 0 228
"Multi-Thresholding" boundary12 setMinMax 0 228
"Multi-Thresholding" boundary12 setButtons 1
"Multi-Thresholding" boundary12 setEditButton 1
"Multi-Thresholding" boundary12 setIncrement 10
"Multi-Thresholding" boundary12 setValue 228
"Multi-Thresholding" boundary12 setSubMinMax 0 228
"Multi-Thresholding" boundary23 setMinMax 0 228
"Multi-Thresholding" boundary23 setButtons 1
"Multi-Thresholding" boundary23 setEditButton 1
"Multi-Thresholding" boundary23 setIncrement 10
"Multi-Thresholding" boundary23 setValue 228
"Multi-Thresholding" boundary23 setSubMinMax 0 228
"Multi-Thresholding" boundary34 setMinMax 0 228
"Multi-Thresholding" boundary34 setButtons 1
"Multi-Thresholding" boundary34 setEditButton 1
"Multi-Thresholding" boundary34 setIncrement 10
"Multi-Thresholding" boundary34 setValue 228
"Multi-Thresholding" boundary34 setSubMinMax 0 228
"Multi-Thresholding" options setValue 0 1
"Multi-Thresholding" options setToggleVisible 0 1
"Multi-Thresholding" options setValue 1 0
"Multi-Thresholding" options setToggleVisible 1 1
"Multi-Thresholding" options setValue 2 0
"Multi-Thresholding" options setToggleVisible 2 1
"Multi-Thresholding" applyTransformToResult 1
"Multi-Thresholding" fire
"Multi-Thresholding" setViewerMask 16383
"Multi-Thresholding" setPickable 1

set hideNewModules 0
[ "Multi-Thresholding" create
 ] setLabel "JRC2018_UNISEX_38um_iso_16bit.labels"
"JRC2018_UNISEX_38um_iso_16bit.labels" setIconPosition 20 267
"JRC2018_UNISEX_38um_iso_16bit.labels" master connect "Multi-Thresholding" "result" 0
"JRC2018_UNISEX_38um_iso_16bit.labels" sharedColormap connect "labels.am"
"JRC2018_UNISEX_38um_iso_16bit.labels" sharedColormap setDefaultColor 0.8 0.8 0.8
"JRC2018_UNISEX_38um_iso_16bit.labels" sharedColormap setDefaultAlpha 0.500000
"JRC2018_UNISEX_38um_iso_16bit.labels" sharedColormap activateLocalRange 1
"JRC2018_UNISEX_38um_iso_16bit.labels" sharedColormap setLocalMinMax 1.000000 8.000000
"JRC2018_UNISEX_38um_iso_16bit.labels" sharedColormap enableAlpha 1
"JRC2018_UNISEX_38um_iso_16bit.labels" sharedColormap enableAlphaToggle 1
"JRC2018_UNISEX_38um_iso_16bit.labels" sharedColormap setAutoAdjustRangeMode 1
"JRC2018_UNISEX_38um_iso_16bit.labels" sharedColormap setColorbarMinMax 1 8
"JRC2018_UNISEX_38um_iso_16bit.labels" fire
"JRC2018_UNISEX_38um_iso_16bit.labels" primary setIndex 0 0
"JRC2018_UNISEX_38um_iso_16bit.labels" fire
"JRC2018_UNISEX_38um_iso_16bit.labels" setViewerMask 16383

set hideNewModules 0
create HxGMC "Generate Surface"
"Generate Surface" setIconPosition 118 315
"Generate Surface" setVar "CustomHelp" {HxGMC}
"Generate Surface" data connect "JRC2018_UNISEX_38um_iso_16bit.labels"
"Generate Surface" fire
"Generate Surface" smoothing setIndex 0 2
"Generate Surface" smoothingExtent setMinMax 1 9
"Generate Surface" smoothingExtent setButtons 0
"Generate Surface" smoothingExtent setEditButton 1
"Generate Surface" smoothingExtent setIncrement 0.533333
"Generate Surface" smoothingExtent setValue 5
"Generate Surface" smoothingExtent setSubMinMax 1 9
"Generate Surface" options setState {item 0 1 item 1 0 }
"Generate Surface" borderOnOff setValue 1
"Generate Surface" algorithmMode setIndex 0 0
"Generate Surface" borderSettings setValue 0 1
"Generate Surface" borderSettings setToggleVisible 0 1
"Generate Surface" borderSettings setValue 1 0
"Generate Surface" borderSettings setToggleVisible 1 1
"Generate Surface" borderSettings setValue 2 0
"Generate Surface" borderSettings setToggleVisible 2 1
"Generate Surface" borderSettings setValue 3 0
"Generate Surface" borderSettings setToggleVisible 3 1
"Generate Surface" materialList setIndex 0 0
"Generate Surface" smoothMaterial setIndex 0 2
"Generate Surface" applyTransformToResult 1
"Generate Surface" fire
"Generate Surface" setViewerMask 16383
"Generate Surface" setPickable 1

set hideNewModules 0
[ load ${SCRIPTDIR}/JRC2018_UNISEX_38um_iso_16bit.surf ] setLabel "JRC2018_UNISEX_38um_iso_16bit.surf"
"JRC2018_UNISEX_38um_iso_16bit.surf" setIconPosition 21 353
"JRC2018_UNISEX_38um_iso_16bit.surf" master connect "Generate Surface" "result" 0
"JRC2018_UNISEX_38um_iso_16bit.surf" fire
"JRC2018_UNISEX_38um_iso_16bit.surf" LevelOfDetail setMinMax -1 -1
"JRC2018_UNISEX_38um_iso_16bit.surf" LevelOfDetail setButtons 1
"JRC2018_UNISEX_38um_iso_16bit.surf" LevelOfDetail setEditButton 1
"JRC2018_UNISEX_38um_iso_16bit.surf" LevelOfDetail setIncrement 1
"JRC2018_UNISEX_38um_iso_16bit.surf" LevelOfDetail setValue -1
"JRC2018_UNISEX_38um_iso_16bit.surf" LevelOfDetail setSubMinMax -1 -1
"JRC2018_UNISEX_38um_iso_16bit.surf" fire
"JRC2018_UNISEX_38um_iso_16bit.surf" setViewerMask 16383

set hideNewModules 0
create HxDisplaySurface "Surface View"
"Surface View" setIconPosition 444 353
"Surface View" setVar "CustomHelp" {HxDisplaySurface}
"Surface View" data connect "JRC2018_UNISEX_38um_iso_16bit.smooth.surf.25k.surf"
"Surface View" colormap disconnect
"Surface View" colormap setDefaultColor 1 0.1 0.1
"Surface View" colormap setDefaultAlpha 0.500000
"Surface View" colormap activateLocalRange 1
"Surface View" colormap setLocalMinMax 0.000000 1.000000
"Surface View" colormap enableAlpha 1
"Surface View" colormap enableAlphaToggle 1
"Surface View" colormap setAutoAdjustRangeMode 1
"Surface View" colormap setColorbarMinMax 0 120
"Surface View" fire
"Surface View" drawStyle setValue 1
"Surface View" fire
"Surface View" drawStyle setSpecularLighting 1
"Surface View" drawStyle setTexture 1
"Surface View" drawStyle setAlphaMode 1
"Surface View" drawStyle setCullingMode 0
"Surface View" drawStyle setNormalBinding 2
"Surface View" drawStyle setSortingMode 1
"Surface View" drawStyle setLineWidth 1.000000
"Surface View" drawStyle setOutlineColor 0 0 0.2
"Surface View" textureWrap setIndex 0 1
"Surface View" selectionMode setIndex 0 0
"Surface View" patch setMinMax 0 1
"Surface View" patch setButtons 1
"Surface View" patch setEditButton 1
"Surface View" patch setIncrement 1
"Surface View" patch setValue 0
"Surface View" patch setSubMinMax 0 1
"Surface View" boundaryId setIndex 0 -1
"Surface View" materials setIndex 0 1
"Surface View" materials setIndex 1 0
"Surface View" colorMode setIndex 0 0
"Surface View" baseTrans setMinMax 0 1
"Surface View" baseTrans setButtons 0
"Surface View" baseTrans setEditButton 1
"Surface View" baseTrans setIncrement 0.1
"Surface View" baseTrans setValue 0.8
"Surface View" baseTrans setSubMinMax 0 1
"Surface View" VRMode setIndex 0 0
"Surface View" colorFieldMappingType setValue 0
"Surface View" setLighting 1
"Surface View" fire
"Surface View" hideBox 1
"Surface View" selectTriangles zab HIJMONNLABANAADAAIAELBHHDGPPKKNIKGACBCFKAFGHOAKKAAAAIAANJCNDJNAAAAAAAAAAAAAAAAAACMJFKHLLABAAAAAAAAAAAAAAAAAAAAAAAAAAAAGAICLPFPFPOOOJMOGN
"Surface View" fire
"Surface View" setViewerMask 16383
"Surface View" setShadowStyle 0
"Surface View" setPickable 1

set hideNewModules 0
create HxSurfaceSmooth "Smooth Surface"
"Smooth Surface" setIconPosition 138 395
"Smooth Surface" setVar "CustomHelp" {HxSurfaceSmooth}
"Smooth Surface" data connect "JRC2018_UNISEX_38um_iso_16bit.surf"
"Smooth Surface" fire
"Smooth Surface" parameters setMinMax 0 -3.40282346638529e+38 3.40282346638529e+38
"Smooth Surface" parameters setValue 0 2
"Smooth Surface" parameters setMinMax 1 -3.40282346638529e+38 3.40282346638529e+38
"Smooth Surface" parameters setValue 1 0.600000023841858
"Smooth Surface" applyTransformToResult 1
"Smooth Surface" fire
"Smooth Surface" setViewerMask 16383
"Smooth Surface" setPickable 1

set hideNewModules 0
[ load ${SCRIPTDIR}/JRC2018_UNISEX_38um_iso_16bit.smooth.surf.100k.am ] setLabel "JRC2018_UNISEX_38um_iso_16bit.smooth.surf.100k.am"
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.100k.am" setIconPosition 21 431
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.100k.am" master connect "Smooth Surface" "result" 0
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.100k.am" fire
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.100k.am" LevelOfDetail setMinMax -1 -1
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.100k.am" LevelOfDetail setButtons 1
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.100k.am" LevelOfDetail setEditButton 1
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.100k.am" LevelOfDetail setIncrement 1
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.100k.am" LevelOfDetail setValue -1
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.100k.am" LevelOfDetail setSubMinMax -1 -1
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.100k.am" fire
"JRC2018_UNISEX_38um_iso_16bit.smooth.surf.100k.am" setViewerMask 16383

set hideNewModules 0

viewer 0 setCameraOrientation -0.998421 0.0171618 0.0534953 3.37539
viewer 0 setCameraPosition 275.851 67.2608 -226.609
viewer 0 setCameraFocalDistance 346.053
viewer 0 setCameraNearDistance -61.0608
viewer 0 setCameraFarDistance 460.028
viewer 0 setCameraType orthographic
viewer 0 setCameraHeight 391.955
viewer 0 setAutoRedraw 1
viewer 0 redraw

"Ortho Slice" data connectTo "AutomaticPointProbe" data
correlationPanel closeTabs
correlationPanel setTabName 0 "Correlation 1"
correlationPanel 0 setLogScalingOnAxis 0 0
correlationPanel 0 setLogScalingOnAxis 1 0

histogramPanel closeTabs
histogramPanel setTabName 0 "Histogram 1"
histogramPanel 0 setLogScalingOnAxis 0 0
histogramPanel 0 setLogScalingOnAxis 1 1

theObjectPool setSelectionOrder JRC2018_UNISEX_38um_iso_16bit.smooth.surf.18k.surf
